networks:
  code-network:
    driver: bridge

services:
  web:
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - '${PROJECTS_PATH}:/repo'
      - './nginx/sites:/etc/nginx/conf.d/'
    networks:
      - code-network

  php:
    build: ./php/82
    volumes:
      - '${PROJECTS_PATH}:/repo'
    networks:
      - code-network
  
  # php56:
  #   build: ./php/56
  #   volumes:
  #     - '${PROJECTS_PATH}:/repo'
  #   networks:
  #     - code-network
  

  # php74:
  #   build: ./php/74
  #   volumes:
  #     - '${PROJECTS_PATH}:/repo'
  #   networks:
  #     - code-network
  db:
    image: 'mysql:8'
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - 'my-db:/var/lib/mysql'
    networks:
      - code-network

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: db
    ports:
      - 8080:8080
    networks:
      - code-network

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - code-network
volumes:
  my-db: null
