version: '3.7'

networks:
  code-network:
    driver: bridge

services:
  web:
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - '${PROJECTS_PATH}:/repo'
      - './nginx/sites:/etc/nginx/conf.d/'
    networks:
      - code-network
  
  php70:
    build: ./php/70
    volumes:
      - '${PROJECTS_PATH}:/repo'
    networks:
      - code-network
  
  php73:
    build: ./php/73
    volumes:
      - '${PROJECTS_PATH}:/repo'
    networks:
      - code-network
  
  php56:
    build: ./php/56
    volumes:
      - '${PROJECTS_PATH}:/repo'
    networks:
      - code-network
  
  db:
    image: 'mysql:5.7'
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - 'my-db:/var/lib/mysql'
    networks:
      - code-network
  
  elasticsearch:
    image: 'elasticsearch:7.4.2'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    networks:
      - code-network
  
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - code-network

volumes:
  my-db: null
  es-data: